site_name: Recipe Book
site_url: https://Jones-Good-Ass-Recipe-book.com
use_directory_urls: false
nav:
    - Home: "index.md"
    - All Recipes: "all_recipes.md"
    - Tags: "tags.md"
theme: journal
extra_css:
    - style.min.css
markdown_extensions:
    - pymdownx.extra
    - pymdownx.details
    - pymdownx.tasklist:
          custom_checkbox: true
          clickable_checkbox: true
